package com.pjatk.awps.model.enums;

public enum Location {
    Aniołki,
    Brętowo,
    Brzeźno,
    Chełm,
    Jasień,
    Kokoszki,
    Letnica,
    Matarnia,
    Młyniska,
    Nowy_Port,
    Oliwa,
    Olszynka,
    Orunia_Górna_Gdańsk_Południe,
    Orunia_Św_Wojciech_Lipce,
    Osowa,
    Piecki_Migowo,
    Przeróbka,
    Przymorze_Małe,
    Przymorze_Wielkie,
    Rudniki,
    Siedlce,
    Stogi,
    Strzyża,
    Suchanino,
    Śródmieście,
    Ujeścisko_Łostowice,
    VII_Dwór,
    Wrzeszcz_Dolny,
    Wrzeszcz_Górny,
    Wyspa_Sobieszewska,
    Wzgórze_Mickiewicza,
    Zaspa_Młyniec,
    Zaspa_Rozstaje,
    Żabianka_Wejhera_Jelitkowo_Tysiąclecia
    }
